name: Renovate

on:
  schedule:
    - cron: 0 */1 * * *
  workflow_dispatch: {}

concurrency: renovate-runner

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain token
        id: obtainToken
        uses: actions/create-github-app-token@v3
        with:
          private-key: ${{ secrets.private_key }}
          client-id: ${{ vars.app_id }}
          owner: ${{ github.repository_owner }}
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.2.5
        with:
          token: '${{ steps.obtainToken.outputs.token }}'
          configurationFile: '.github/renovate.json'
